import serial
import logger

class PICComm():
    '''Define a class to dictate the protocol for PIC comms.'''

    def __init__(self, port, baud_rate, logger, timeout=0.05):
        '''This function defines the PIC protocol class
        
        Parameters
        port: str, format 'COM_' where _ is int
            COM port for DDS boards
        baud_rate: int
            baud rate for COM port serial communication
        logger: logger, generated by LogManager
            means to write comments to the program log
        timeout: int
            ms to wait before timing out communications
        '''

        # Extract communication information
        self.port = port
        self.baud_rate = baud_rate

        # Logging for PIC
        self.logger = logger

        #Open serial port 
        try:
            self.ser = serial.Serial(self.port, self.baud_rate, timeout=timeout) 
        except serial.SerialException as e:
            self.logger.error(f'Failed to open serial port {self.port}: {e}')
            self.ser = None


        
    def pic_comm(self, command_string, data_array, read_byte_count):
        '''This function takes an input byte array and command string, similar to the PIC Comm LabVIEW VI.
        
        Parameters
        command_string: str
            letter string to tell PIC controller what to do
        data_array: array of bytes
            array of bytes to pass to PIC controller
        read_byte_count: int
            number of bytes to read after PIC comms
        '''

        # Initialise bit list for extra ones
        ones_list = [1] * (read_byte_count - len(data_array))

        # Convert command string to U8
        command_byte = ord(command_string)

        # Determine number of bytes to send
        pic_byte_array = bytearray([command_byte] + list(data_array) + ones_list)

        # Write byte array to PIC
        response = self.pic_comm_byte_array(pic_byte_array)

        return response


    def pic_comm_byte_array(self, byte_array, verbose=False):
        '''This function sends byte arrays to the PIC controller.
        
        Parameters
        byte_array: array of bytes
            array of bytes to send to PIC controller
        verbose: boolean
            True to return sent string and response, False for response byte string only
        
        '''
        
        try:
            
            if not self.ser or not self.ser.is_open:
                self.logger.error("Serial port is not open.")
                return []

            else:
                
                # Try to write byte array to serial port
                self.ser.write(byte_array)
                
                # Sleep for 1 ms (units of time.sleep is seconds) - you may want to remove this or add in a non-blocking alternative
                time.sleep(0.001)  # Adjust the sleep time if necessary
                
                # Read response from serial port
                response = self.ser.read(64)  # Adjust the number of bytes to read if necessary
                
                # Emit response to be read by DDSWidget
                #self.signals.response_signal.emit(response)
                
                if verbose:
                    
                    # Make a string with response
                    sent_string = f"Sent= {','.join(str(b) for b in byte_array)}"
                    
                    # Emit verbose response 
                    self.logger.debug(sent_string, '\nResponse:', response)

                return response
                
        except serial.SerialException as e:
            
            # Send error message to log
            self.logger.error(f'Serial communication error (send_byte_array_to_pic): {e}', exc_info=True)
            
        except Exception as e:
            
            # Send error message to log
            self.logger.error(f'Unexpected error (send_byte_array_to_pic: {e}', exc_info=True)


    def pic_comm_command(self, command_char, verbose=False):
        '''Send a single character command to the PIC controller over serial.

        Parameters
        command_char : str
            A single-character string to send (e.g. 'g' for start).
        verbose : bool
            If True, logs the sent command and received response.
        '''

        try:
            if not self.ser or not self.ser.is_open:
                self.logger.error("Serial port is not open.")
                return None

            # Convert character to bytes
            command_bytes = command_char.encode('latin1')  # or 'ascii'

            # Write to serial
            self.ser.write(command_bytes)

            # Read response (expecting a single byte)
            response = self.ser.read(1)

            if verbose:
                response_str = response.decode('latin1') if response else 'None'
                self.logger.debug(f"Sent command: '{command_char}' | Response: '{response_str}'")

            return response

        except serial.SerialException as e:
            self.logger.error(f'Serial communication error (pic_comm_command): {e}', exc_info=True)

        except Exception as e:
            self.logger.error(f'Unexpected error (pic_comm_command): {e}', exc_info=True)



    def shutdown(self):
        '''This function shuts down the DDS when the program is stopped or closed.'''

        # Close serial port
        if self.ser and self.ser.is_open:
            self.ser.close()


